document.write('<i>https://raw.githubusercontent.com/pfot/fot/main/авангард/при5 авангард 01.jpg</i><b>при5 авангард 01.jpg</b>');
document.write('<i>https://raw.githubusercontent.com/pfot/fot/main/авангард/при5 авангард 02t.jpg</i><b>при5 авангард 02t.jpg</b>');
document.write('<i>https://raw.githubusercontent.com/pfot/fot/main/авангард/при5 авангард 03.jpg</i><b>при5 авангард 03.jpg</b>');
document.write('<i>https://raw.githubusercontent.com/pfot/fot/main/авангард/при5 авангард 04t.jpg</i><b>при5 авангард 04t.jpg</b>');
document.write('<i>https://raw.githubusercontent.com/pfot/fot/main/авангард/при5 авангард 05.jpg</i><b>при5 авангард 05.jpg</b>');
document.write('<i>https://raw.githubusercontent.com/pfot/fot/main/авангард/при5 авангард 06.jpg</i><b>при5 авангард 06.jpg</b>');
document.write('<i>https://raw.githubusercontent.com/pfot/fot/main/авангард/при5 авангард 07.jpg</i><b>при5 авангард 07.jpg</b>');
document.write('<i>https://raw.githubusercontent.com/pfot/fot/main/авангард/при5 авангард 08.jpg</i><b>при5 авангард 08.jpg</b>');
document.write('<i>https://raw.githubusercontent.com/pfot/fot/main/авангард/при5 авангард 09.jpg</i><b>при5 авангард 09.jpg</b>');
document.write('<i>https://raw.githubusercontent.com/pfot/fot/main/авангард/при5 авангард 10t.jpg</i><b>при5 авангард 10t.jpg</b>');
document.write('<i>https://raw.githubusercontent.com/pfot/fot/main/авангард/при5 авангард 11.jpg</i><b>при5 авангард 11.jpg</b>');
document.write('<i>https://raw.githubusercontent.com/pfot/fot/main/авангард/при5 авангард 12.jpg</i><b>при5 авангард 12.jpg</b>');
document.write('<i>https://raw.githubusercontent.com/pfot/fot/main/авангард/при5 авангард 13.jpg</i><b>при5 авангард 13.jpg</b>');
document.write('<i>https://raw.githubusercontent.com/pfot/fot/main/авангард/при5 авангард 14.jpg</i><b>при5 авангард 14.jpg</b>');
document.write('<i>https://raw.githubusercontent.com/pfot/fot/main/авангард/при5 авангард 15.jpg</i><b>при5 авангард 15.jpg</b>');
document.write('<i>https://raw.githubusercontent.com/pfot/fot/main/авангард/при5 авангард 16t.jpg</i><b>при5 авангард 16t.jpg</b>');
document.write('<i>https://raw.githubusercontent.com/pfot/fot/main/авангард/при5 авангард 17t.jpg</i><b>при5 авангард 17t.jpg</b>');
document.write('<i>https://raw.githubusercontent.com/pfot/fot/main/авангард/при5 авангард 18.jpg</i><b>при5 авангард 18.jpg</b>');
document.write('<i>https://raw.githubusercontent.com/pfot/fot/main/авангард/при5 авангард 19.jpg</i><b>при5 авангард 19.jpg</b>');
document.write('<i>https://raw.githubusercontent.com/pfot/fot/main/авангард/при5 авангард 20.jpg</i><b>при5 авангард 20.jpg</b>');
document.write('<i>https://raw.githubusercontent.com/pfot/fot/main/авангард/при5 авангард 21t.jpg</i><b>при5 авангард 21t.jpg</b>');
document.write('<i>https://raw.githubusercontent.com/pfot/fot/main/авангард/при5 авангард 22t.jpg</i><b>при5 авангард 22t.jpg</b>');
document.write('<i>https://raw.githubusercontent.com/pfot/fot/main/авангард/при5 авангард 23t.jpg</i><b>при5 авангард 23t.jpg</b>');
document.write('<i>https://raw.githubusercontent.com/pfot/fot/main/авангард/при5 авангард 24t.jpg</i><b>при5 авангард 24t.jpg</b>');
document.write('<i>https://raw.githubusercontent.com/pfot/fot/main/авангард/при5 авангард 25t.jpg</i><b>при5 авангард 25t.jpg</b>');
document.write('<i>https://raw.githubusercontent.com/pfot/fot/main/авангард/при5 авангард 26t.jpg</i><b>при5 авангард 26t.jpg</b>');
document.write('<i>https://raw.githubusercontent.com/pfot/fot/main/авангард/при5 авангард вход 01t.jpg</i><b>при5 авангард вход 01t.jpg</b>');
document.write('<i>https://raw.githubusercontent.com/pfot/fot/main/авангард/при5 авангард вход 02t.jpg</i><b>при5 авангард вход 02t.jpg</b>');
document.write('<i>https://raw.githubusercontent.com/pfot/fot/main/авангард/при5 авангард вход 03t.jpg</i><b>при5 авангард вход 03t.jpg</b>');
document.write('<i>https://raw.githubusercontent.com/pfot/fot/main/авангард/при5 авангард вход 04t.jpg</i><b>при5 авангард вход 04t.jpg</b>');
document.write('<i>https://raw.githubusercontent.com/pfot/fot/main/авангард/при5 авангард вход 05.jpg</i><b>при5 авангард вход 05.jpg</b>');
document.write('<i>https://raw.githubusercontent.com/pfot/fot/main/авангард/при5 авангард вход 06.jpg</i><b>при5 авангард вход 06.jpg</b>');
document.write('<i>https://raw.githubusercontent.com/pfot/fot/main/авангард/при5 авангард вход 07t.jpg</i><b>при5 авангард вход 07t.jpg</b>');
document.write('<i>https://raw.githubusercontent.com/pfot/fot/main/авангард/при5 авангард вход 08t.jpg</i><b>при5 авангард вход 08t.jpg</b>');
document.write('<i>https://raw.githubusercontent.com/pfot/fot/main/авангард/при5 авангард вход 09t.jpg</i><b>при5 авангард вход 09t.jpg</b>');
document.write('<i>https://raw.githubusercontent.com/pfot/fot/main/авангард/при5 авангард вход 10t.jpg</i><b>при5 авангард вход 10t.jpg</b>');
document.write('<i>https://raw.githubusercontent.com/pfot/fot/main/авангард/при5 авангард вход 11.jpg</i><b>при5 авангард вход 11.jpg</b>');
document.write('<i>https://raw.githubusercontent.com/pfot/fot/main/авангард/при5 авангард стенд 01t.jpg</i><b>при5 авангард стенд 01t.jpg</b>');
document.write('<i>https://raw.githubusercontent.com/pfot/fot/main/авангард/при5 авангард стенд 02.jpg</i><b>при5 авангард стенд 02.jpg</b>');
document.write('<i>https://raw.githubusercontent.com/pfot/fot/main/авангард/при5 авангард стенд 03.jpg</i><b>при5 авангард стенд 03.jpg</b>');
document.write('<i>https://raw.githubusercontent.com/pfot/fot/main/авангард/при5 авангард стенд 04.jpg</i><b>при5 авангард стенд 04.jpg</b>');
document.write('<i>https://raw.githubusercontent.com/pfot/fot/main/авангард/при5 авангард стенд 05.jpg</i><b>при5 авангард стенд 05.jpg</b>');
document.write('<i>https://raw.githubusercontent.com/pfot/fot/main/авангард/при5 авангард стенд 06.jpg</i><b>при5 авангард стенд 06.jpg</b>');
